version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time arguments for Next.js public environment variables
        - NEXT_PUBLIC_API_URL=http://172.16.3.6:3001
        - NEXT_PUBLIC_WS_URL=http://172.16.3.6:3001
        - NEXT_PUBLIC_LOGIN_USERNAME=admin
        - NEXT_PUBLIC_LOGIN_PASSWORD=secure123!
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://checkin_user:checkin_password@postgres:5432/checkin_db
      # Runtime environment variables (can override build-time values)
      - NEXT_PUBLIC_API_URL=http://172.16.3.6:3001
      - NEXT_PUBLIC_WS_URL=http://172.16.3.6:3001
      - NEXT_PUBLIC_LOGIN_USERNAME=admin
      - NEXT_PUBLIC_LOGIN_PASSWORD=secure123!
      # Prisma environment variables for Docker ARM64
      - PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-3.0.x
      - PRISMA_QUERY_ENGINE_BINARY=linux-arm64-openssl-3.0.x
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - checkin-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=checkin_db
      - POSTGRES_USER=checkin_user
      - POSTGRES_PASSWORD=checkin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - checkin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkin_user -d checkin_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  checkin-network:
    driver: bridge 