version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: checkin_user
      POSTGRES_PASSWORD: checkin_password
      POSTGRES_DB: checkin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkin_user -d checkin_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 