version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        # Build-time arguments for Next.js public environment variables
        - NEXT_PUBLIC_API_URL=http://172.16.3.6:3001
        - NEXT_PUBLIC_WS_URL=http://172.16.3.6:3001
        - NEXT_PUBLIC_LOGIN_USERNAME=admin
        - NEXT_PUBLIC_LOGIN_PASSWORD=secure123!
    ports:
      - "3000:3000"
    environment:
      # Runtime environment variables (can override build-time values)
      - NEXT_PUBLIC_API_URL=http://172.16.3.6:3001
      - NEXT_PUBLIC_WS_URL=http://172.16.3.6:3001
      - NEXT_PUBLIC_LOGIN_USERNAME=admin
      - NEXT_PUBLIC_LOGIN_PASSWORD=secure123!
      - DATABASE_URL=postgresql://checkin_user:checkin_password@postgres:5432/checkin_db
    depends_on:
      - postgres
      - backend
    networks:
      - checkin-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://checkin_user:checkin_password@postgres:5432/checkin_db
      - PORT=3001
      - NODE_ENV=production
      # Remove hardcoded CORS to allow dynamic origin detection
      # - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
    networks:
      - checkin-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=checkin_db
      - POSTGRES_USER=checkin_user
      - POSTGRES_PASSWORD=checkin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - checkin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkin_user -d checkin_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  checkin-network:
    driver: bridge 